core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('items/', views.products, name='items'),
    path('', views.HomeView.as_view(), name='home'),
    path('products/<slug:slug>/', views.ProductDetailView.as_view(), name='products'),
    path('order-summary/', views.OrderSummaryView.as_view(), name='order-summary'),
    path('add-to-cart/<slug:slug>/', views.add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<slug:slug>/', views.remove_from_cart, name='remove-from-cart'),
    path('remove-single-item-from-cart/<slug:slug>/', views.remove_single_item_from_cart, name='remove-single-item-from-cart'),
] 

payment/urls.py
from django.urls import path
from . import views

app_name = 'payment'

urlpatterns = [
    path('payment/', views.PaymentView.as_view(), name='payment'),
    path('payment-option/<payment_option>/', views.PaymentOptionView.as_view(), name='payment-option'),
] 

simple_commerce/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('core/', include('core.urls')),
    path('payment/', include('payment.urls')),
]

if settings.DEBUG:
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))] 
    
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.conf import settings
from django.shortcuts import reverse
from django_countries.fields import CountryField


CATEGORY_CHOICES = (
    ('O', 'Official'),
    ('SW', 'Sport wear'),
    ('OW', 'Outwear'),
    ('C', 'Casual'),
    ('I', 'Indoors'),
)

LABEL_CHOICES = (
    ('P', 'primary'),
    ('S', 'secondary'),
    ('D', 'danger'),
)

class Item(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=2)
    label = models.CharField(choices=LABEL_CHOICES, max_length=1)
    slug = models.SlugField()
    description = models.TextField(default="This is a product description")
    image = models.ImageField(blank=True, null=True, default = "")
    
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("core:products", kwargs={'slug': self.slug})
    
    def get_add_to_cart_url(self):
        return reverse("core:add-to-cart", kwargs={'slug': self.slug})
    
    def get_remove_from_cart_url(self):
        return reverse("core:remove-from-cart", kwargs={'slug': self.slug})
    
    @property
    def imageUrl(self):
        try:
            url = self.image.url 
        except:
            url = ''
        return url
    

class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, blank=True, null=True)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    
    def __str__(self):
        return f"{self.quantity} of {self.item.title}"
    
    def get_total_price(self):
        return self.quantity * self.item.price
    
    def get_total_discount_price(self):
        return self.quantity * self.item.discount_price
    
    def get_amount_saved(self):
        return self.get_total_price() - self.get_total_discount_price()
    
    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_price()
        else:
            return self.get_total_price()


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    payment_address = models.ForeignKey('PaymentAddress', on_delete=models.SET_NULL, blank=True, null=True)
    payment = models.ForeignKey('Payment', on_delete=models.SET_NULL, blank=True, null=True)
    
    def __str__(self):
        return self.user.username
    
    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        return total
    
    
class PaymentAddress(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    county = models.CharField(max_length=100)
    street_address = models.CharField(max_length=100)
    country = CountryField(multiple=True)
    zip = models.CharField(max_length=100)
    
    def __str__(self):
        return self.user.username
    
    
class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=40)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.user.username

payment/forms.py
from django import forms
from django_countries.fields import CountryField
from django_countries.widgets import CountrySelectWidget

PAYMENT_CHOICES = (
    ('M', 'Lipa na Mpesa'),
    ('C', 'Credit card'),
    ('P', 'Paypal'),
    ('S', 'Stripe'),
)

class PaymentForm(forms.Form):
    county = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'County Address'
    }))
    street_address = forms.CharField(required=False, widget=forms.TextInput(attrs={
        'placeholder': 'Street Address'
    }))
    country = CountryField(blank_label='(select country)').formfield(
        widget=CountrySelectWidget(attrs={
        'class': 'custom-select d-block w-100',
        'id': 'zip'
    }))
    zip = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control'
    }))
    same_shipping_address = forms.BooleanField(required=False)
    save_info = forms.BooleanField(required=False)
    payment_option = forms.ChoiceField(widget=forms.RadioSelect, choices=PAYMENT_CHOICES)

payment/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView, View
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from django.conf import settings

from .forms import PaymentForm
from core.models import Item, OrderItem, Order, PaymentAddress, Payment

import stripe
stripe.api_key = settings.STRIPE_SECRET_KEY


class PaymentView(View):
    def get(self, *args, **kwargs):
        form = PaymentForm()
        context = {
            'form': form
        }        
        return render(self.request, "checkout-page.html", context)
    
    def post(self, *args, **kwargs):
        form = PaymentForm(self.request.POST or None)
        try:
            order = Order.objects.get(user=self.request.user, ordered=False)
            if form.is_valid():
                county = form.cleaned_data['county']
                street_address = form.cleaned_data['street_address']        
                country = form.cleaned_data['country']
                zip = form.cleaned_data['zip']
                # same_shipping_address = form.cleaned_data('same_billing_address')
                # save_info = form.cleaned_data('save_info')
                payment_option = form.cleaned_data['payment_option']
                payment_address = PaymentAddress( 
                    user=self.request.user,
                    county=county,
                    street_address=street_address,
                    country=country,
                    zip=zip,        
                )
                payment_address.save()
                order.payment_address = payment_address
                
                return redirect("payment:payment")
            messages.warning(self.request, "Failed payment")
            
        except ObjectDoesNotExist:
            messages.error(self.request, "You do not have an order")
            return redirect("core:order-summary")
        
        
class PaymentOptionView(View):
    def get(self, *args, **kwargs):
               
        return render(self.request, "payment.html", {})
    
    def post(self, *args, **kwargs):
        order = Order.objects.get(user=self.request.user, ordered=False)
        token = self.request.POST.get('stripeToken')
        amount=order.get_total()
        charge = stripe.Charge.create(
            amount=amount,
            currency="Ksh",
            source=token,
            description="Charge for purchased goods"
        )
        
        # create the payment
        payment = Payment()
        payment.stripe_charge_id = charge['id']
        payment.user = self.request.user
        payment.amount = amount
        payment.save()
        
        # assign payment to user
        order.ordered = True
        order.payment = payment
        order.save()
    

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">

  <title>{% block head_title %}{% endblock %}</title>
  {% block extra_head %}
  {% endblock %}

  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
  <!-- Bootstrap core CSS -->
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <!-- Material Design Bootstrap -->
  <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
  <!-- Your custom styles (optional) -->
  <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
  <style type="text/css">
    html,
    body,
    header,
    .carousel {
      height: 60vh;
    }

    @media (max-width: 740px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

  </style>

  {% include "navbar.html" %}

</head>


<body>
    <div class="mt-5 pt-4">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissable fade show" role="alert">
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endfor %}
        {% endif %}
    </div>
    
    {% block content %}
    {% endblock %}

    {% block extra_body %}
    {% endblock %}

    {% include "footer.html" %}
    {% include "scripts.html" %}
</body>
</html>

templates/footer.html
  <!--Footer-->
  <footer class="page-footer text-center font-small mt-4 wow fadeIn">

    
    <hr class="my-4">
    
    <!-- Social icons --> 
    <div class="pb-4">
        <a href="https://www.facebook.com/mdbootstrap" target="_blank">
            <i class="fab fa-facebook-f mr-3"></i>
        </a>
    
        <a href="https://twitter.com/MDBootstrap" target="_blank">
            <i class="fab fa-twitter mr-3"></i>
        </a>
    
        <a href="https://www.youtube.com/watch?v=7MUISDJ5ZZ4" target="_blank">
            <i class="fab fa-youtube mr-3"></i>
        </a>
    
        <a href="https://plus.google.com/u/0/b/107863090883699620484" target="_blank">
            <i class="fab fa-google-plus-g mr-3"></i>
        </a>
    
        <a href="https://dribbble.com/mdbootstrap" target="_blank">
            <i class="fab fa-dribbble mr-3"></i>
        </a>
    
        <a href="https://pinterest.com/mdbootstrap" target="_blank">
            <i class="fab fa-pinterest mr-3"></i>
        </a>
    
        <a href="https://github.com/mdbootstrap/bootstrap-material-design" target="_blank">
            <i class="fab fa-github mr-3"></i>
        </a>
    
        <a href="http://codepen.io/mdbootstrap/" target="_blank">
            <i class="fab fa-codepen mr-3"></i>
        </a>
    </div>
    <!-- Social icons --> 
    
    <!--Copyright-->
    <div class="footer-copyright py-3">
        © 2020 Copyright:
        <a href="https://mdbootstrap.com/education/bootstrap/" target="_blank"> Jimshop.com </a>
    </div>
    <!--/.Copyright-->
    
    </footer>
    <!--/.Footer-->

templates/home-page.html
{% extends 'base.html' %}

{% block content%}

<body>

  <!--Main layout-->
  <main>
    <div class="container">

      <!--Navbar-->
      <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

        <!-- Navbar brand -->
        <span class="navbar-brand">Categories:</span>

        <!-- Collapse button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
          aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="basicExampleNav">

          <!-- Links -->
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">All
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Official</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Sport wears</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Outwears</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Casual</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Indoors</a>
            </li>

          </ul>
          <!-- Links -->

          <form class="form-inline">
            <div class="md-form my-0">
              <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            </div>
          </form>
        </div>
        <!-- Collapsible content -->

      </nav>
      <!--/.Navbar-->

      <!--Section: Products v.3-->
      <section class="text-center mb-4">

        <!--Grid row-->
        <div class="row wow fadeIn">

          <!--Grid column-->
          {% for item in object_list %}
          <div class="col-lg-3 col-md-6 mb-4">

            <!--Card-->
            <div class="card">

              <!--Card image https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12.jpg -->
              <div class="view overlay">
                <img src="{{item.imageUrl}}" class="card-img-top" 
                  alt="">
                <a href="{{ item.get_absolute_url }}">
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>
              <!--Card image-->

              <!--Card content-->
              <div class="card-body text-center">
                <!--Category & Title-->
                <a href="" class="grey-text">
                  <h5>{{ item.get_category_display }}</h5>
                </a>
                <h5>
                  <strong>
                    <a href="{{ item.get_absolute_url }}" class="dark-grey-text">{{ item.title }}
                      <span class="badge badge-pill {{ item.get_label_display }}-color">NEW</span>
                    </a>
                  </strong>
                </h5>

                <h4 class="font-weight-bold blue-text">
                  <strong>ksh
                    {% if item.discount_price %}
                      {{ item.discount_price }}
                    {% else %}
                      {{ item.price }}
                    {% endif %}
                  </strong>
                </h4>

              </div>
              <!--Card content-->

            </div>
            <!--Card-->

          </div>
          {% endfor %}
          <!--Grid column-->   

        </div>
        <!--Grid row-->

        

      </section>
      <!--Section: Products v.3-->

      <!--Pagination-->
      {% if is_paginated %}
        <nav class="d-flex justify-content-center wow fadeIn">
          <ul class="pagination pg-blue">

            <!--Arrow left-->
            {% if page_obj.has_previous %}
              <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                  <span aria-hidden="true">&laquo;</span>
                  <span class="sr-only">Previous</span>
                </a>
              </li>
            {% endif %}

            <li class="page-item active">
              <a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}
                <span class="sr-only">(current)</span>
              </a>
            </li>

            {% if page_obj.has_next %}
              <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                  <span aria-hidden="true">&raquo;</span>
                  <span class="sr-only">Next</span>
                </a>
              </li>
            {% endif %}
          </ul>
        </nav>
      {% endif %}
      <!--Pagination-->

    </div>
  </main>
  <!--Main layout-->





</body>

</html>

{% endblock %}

templates/item_list.html
<h2>Here is a list of items</h2>

{% for item in items %}
    {{ item }}
{% endfor %}

templates/navbar.html
{% load cart_template_tags %}

<!-- Navbar -->
<nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
    <div class="container">

        <!-- Brand --> 
        <a class="navbar-brand waves-effect" href="{% url 'core:home' %}">
            <strong class="blue-text">@jimmy's</strong>
        </a>

        <!-- Collapse -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Links -->
        <div class="collapse navbar-collapse" id="navbarSupportedContent">

            <!-- Left -->
            <ul class="navbar-nav mr-auto">
            {% comment %} <li class="nav-item active">
                <a class="nav-link waves-effect" href="{% url 'core:home' %}">Home
                <span class="sr-only">(current)</span>
                </a>
            </li> {% endcomment %}
            <li class="nav-item">
                <a class="nav-link waves-effect" href="https://mdbootstrap.com/docs/jquery/" target="_blank">About Shop</a>
            </li>
            <li class="nav-item">
                <a class="nav-link waves-effect" href="https://mdbootstrap.com/docs/jquery/getting-started/download/"
                target="_blank">Free download</a>
            </li>
            <li class="nav-item">
                
                <a class="nav-link waves-effect" href="{% url 'payment:payment' %}">Payment</a>
            </li>
            </ul>

            <!-- Right --> 
            <ul class="navbar-nav nav-flex-icons">
                {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a href="{% url 'core:order-summary' %}" class="nav-link waves-effect">
                        <span class="badge red z-depth-1 mr-1"> {{ request.user|cart_item_count }} </span>
                        <i class="fas fa-shopping-cart"></i>
                        <span class="clearfix d-none d-sm-inline-block"> Cart </span>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'account_logout' %}" class="nav-link waves-effect">
                        <span class="clearfix d-none d-sm-inline-block"> Logout </span>
                    </a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a href="{% url 'account_login' %}" class="nav-link waves-effect">
                        <span class="clearfix d-none d-sm-inline-block"> Login </span>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'account_signup' %}" class="nav-link waves-effect">
                        <span class="clearfix d-none d-sm-inline-block"> SignUp </span>
                    </a>
                </li>
                {% endif %}
            </ul>

        </div>

    </div>
</nav>
<!-- Navbar -->

templates/order_summary.html
{% extends 'base.html' %}

{% block content%}

    <div class="container">
        <h2>Order Summary</h2>
        <table class="table caption-top">
           

            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Item Title</th>
                    <th scope="col">Price</th>
                    <th scope="col">Quantity</th>
                    <th scope="col">Total Price</th>
                </tr>
            </thead>

            <tbody>
                {% for order_item in object.items.all %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>{{ order_item.item.title }}</td>
                        <td>{{ order_item.item.price }}</td>
                        <td>
                            <a href="{% url 'core:remove-single-item-from-cart' order_item.item.slug %}"><i class="fas fa-minus mr-1"></i></a>
                                {{ order_item.quantity }}
                            <a href="{% url 'core:add-to-cart' order_item.item.slug %}"><i class="fas fa-plus ml-1"></i></a>
                        </td>
                        <td>
                            {% if order_item.item.discount_price %}
                                Ksh{{ order_item.get_total_discount_price }}
                                <span class="badge badge-secondary">Saving Ksh{{ order_item.get_amount_saved }}</span>
                                
                            {% else %}
                                Ksh{{ order_item.get_total_price }}
                            {% endif %}
                            <a href="{% url 'core:remove-from-cart' order_item.item.slug %}">
                                <i class="fas fa-trash float-right"></i>
                            </a>
                        </td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="4">Your cart is empty</td>
                    </tr>
                    <tr>
                        <td colspan="4">
                            <a href="btn btn-primary float-right" href="{% url 'core:home' %}">Continue shopping</a>
                        </td>
                    </tr>
                {% endfor %}

                {% if object.get_total %}
                    <tr>
                        <td colspan="4"><b>Total order Price: </b></td>
                        <td>Ksh{{ object.get_total }}</td>
                    </tr>
                    <tr>
                        <td colspan="4">
                            <a class="btn btn-primary float-right ml-2" href="{% url 'core:home' %}">Continue shopping</a>
                            <a class="btn btn-warning float-right" href="{% url 'payment:payment' %}">Proceed to pay</a>
                        </td>
                    </tr>
                {% endif %}

            </tbody>
        </table>
    </div>



{% endblock %}

templates/product-page.html
{% extends 'base.html' %}

{% block content  %}

<body>

  <!--Main layout-->
  <main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/14.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <!--Content-->
          <div class="p-4">

            <div class="mb-3">
              <a href="">
                <span class="badge purple mr-1">{{ object.get_category_display }}</span>
              </a>
            </div>

            <p class="lead">
              {% if object.discount_price %}
                <span class="mr-1">
                  <del>Ksh{{ object.price }}</del>
                </span>
                <span>Ksh{{ object.discount_price }}</span>
              {% else %}
                {{ object.price }}
              {% endif %}
            </p>

            <p class="lead font-weight-bold">Description</p>

            <p>{{ object.description }}</p>

            <a href="{{ object.get_add_to_cart_url }}" class="btn btn-primary btn-md my-0 p">Add to cart
              <i class="fas fa-shopping-cart ml-1"></i>
            </a>

            <a href="{{ object.get_remove_from_cart_url }}" class="btn btn-danger btn-md my-0 p">Remove from cart
            </a>

          </div>
          <!--Content-->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <hr>

      <!--Grid row-->
      <div class="row d-flex justify-content-center wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 text-center">

          <h4 class="my-4 h4">Additional information</h4>

          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus suscipit modi sapiente illo soluta odit
            voluptates,
            quibusdam officia. Neque quibusdam quas a quis porro? Molestias illo neque eum in laborum.</p>

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-lg-4 col-md-12 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/11.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/12.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/13.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

    </div>
  </main>
  <!--Main layout-->

 
</body>

</html>

{% endblock %}

templates/scripts.html
{% load static %}

<!-- SCRIPTS -->
<!-- JQuery -->
<script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
<!-- Initializations -->
<script type="text/javascript">
// Animations initialization
new WOW().init();

</script>